version: '3'

services:

  airflow-webserver:
    image: apache/airflow:2.9.2
    container_name: airflow-webserver
    restart: always
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://${USER}:${PASSWORD}@${HOST}:${PORT}/${DB}
      PYTHONPATH: /opt/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: >
        mysqlclient mysql-connector-python
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./ETL:/opt/airflow/ETL
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.2
    container_name: airflow-scheduler
    restart: always
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://${USER}:${PASSWORD}@${HOST}:${PORT}/${DB}
      PYTHONPATH: /opt/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: >
        mysqlclient mysql-connector-python
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./ETL:/opt/airflow/ETL
    depends_on:
      - airflow-init
    command: scheduler

  airflow-init:
    image: apache/airflow:2.9.2
    container_name: airflow-init
    restart: on-failure
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://${USER}:${PASSWORD}@${HOST}:${PORT}/${DB}
      PYTHONPATH: /opt/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: >
        mysqlclient mysql-connector-python
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./ETL:/opt/airflow/ETL
    entrypoint: >
      bash -c "
        sleep 10 &&
        airflow db init &&
        airflow users create --username admin --password admin123 --firstname Admin --lastname User --role Admin --email admin@example.com
      "

volumes:
  logs:
